package:
  name: networkx
  version: '2.4'
requirements:
  run:
  - decorator
  - setuptools
  # Upstream NetworkX has these as "soft" dependencies, but it's more
  # convenient to have them come in automatically.
  - matplotlib
  - numpy
source:
  sha256: f8f4ff0b6f96e4f9b16af6b84622597b5334bf9cae8cf9b2e42e7985d5c95c64
  url: https://files.pythonhosted.org/packages/bf/63/7b579dd3b1c49ce6b7fd8f6f864038f255201410905dd183cf7f4a3845cf/networkx-2.4.tar.gz
